theme: "dark" # "light" # "dark"
font_size: 20
plot_font_size: 22
plot_point_size: 10
plot_line_width: 2
icon_size: 20

# --------------
# IDENTIFICATION
# --------------
A: 10.0
freq: 1.0

J: 0.2 # 0.11
B: 0.5 # 1.95
k: 1.0

ident_plot_range: 15.0
freq_plot_range: 3.0

# --------------
# SERVO SYSTEM
# --------------
delta: 2
alpha: 0.7

kx: 16.0
kv: 0.0

lambda_plot_range_x: 22
lambda_plot_range_y: 25
k_plot_range_x: 350
k_plot_range_y: 15
servo_plot_range: 10.0
plot_draw_rate: 25
