plot_font_size: 36
plot_point_size: 20
plot_line_width: 3
icon_size: 40

# --------------
# IDENTIFICATION
# --------------
A: 10.0
freq: 1.0

J: 0.11
B: 1.95
k: 1.0

ident_plot_range: 20.0

# --------------
# SERVO SYSTEM
# --------------
delta: 2
alpha: 0.7

kx: 16.0
kv: 0.0

servo_plot_range: 10.0
