plot_font_size: 36
plot_point_size: 20
plot_line_width: 3

# --------------
# IDENTIFICATION
# --------------
A: 5.0
freq: 1.0

J: 0.09
B: 1.85
k: 0.0

# --------------
# SERVO SYSTEM
# --------------
delta: 2
alpha: 0.7

kx: 16.0
kv: 0.0
