# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(939, 773)
        Dialog.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.mainLay = QtWidgets.QVBoxLayout()
        self.mainLay.setObjectName("mainLay")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.identModeBtn = QtWidgets.QPushButton(Dialog)
        self.identModeBtn.setMinimumSize(QtCore.QSize(400, 0))
        self.identModeBtn.setObjectName("identModeBtn")
        self.horizontalLayout.addWidget(self.identModeBtn)
        self.servoModeBtn = QtWidgets.QPushButton(Dialog)
        self.servoModeBtn.setMinimumSize(QtCore.QSize(400, 0))
        self.servoModeBtn.setObjectName("servoModeBtn")
        self.horizontalLayout.addWidget(self.servoModeBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.mainLay.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.mainLay, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Feedback Control Systems Lab"))
        self.identModeBtn.setText(_translate("Dialog", "Identification"))
        self.servoModeBtn.setText(_translate("Dialog", "Servo System"))
